#百度直连
baidu: &baidu
  type: http
  port: 443
  headers:
    X-T5-Auth: 683556433
    Host: 153.3.236.22:443
#钉钉直连
addons: &addons
  type: http
  port: 443
  headers:
    withAt: ikun.dingtalk.com
    X-T5-Auth: 683556433
    Host: 153.3.236.22:443
mixed-port: 7890
allow-lan: true
bind-address: '*'
mode: rule
log-level: error
dns:
  enable: true
  ipv6: false
  default-nameserver: [223.5.5.5, 119.29.29.29]
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  nameserver: ['https://doh.pub/dns-query', 'https://dns.alidns.com/dns-query']
  fallback: ['https://doh.dns.sb/dns-query', 'https://dns.cloudflare.com/dns-query', 'https://120.53.53.53/dns-query', dot.pub]
  fallback-filter: {geo: [240.0.0.0/4, 0.0.0.0/32]}
proxies:
  - name: 南京联通
    server: 153.3.237.117
    !!merge <<: *baidu
  - name: 苏州联通
    server: 157.0.148.53
    !!merge <<: *baidu
  - name: 保定联通
    server: 110.242.70.69
    !!merge <<: *baidu
  - name: 联通保定
    server: 110.242.70.68
    !!merge <<: *baidu
  - name: 苏州电信
    server: 180.97.93.202
    !!merge <<: *baidu
  - name: 北京电信
    server: 220.181.33.174
    !!merge <<: *baidu
  - name: 南京电信
    server: 180.101.50.249
    !!merge <<: *baidu
  - name: 电信南京
    server: 180.101.50.208
    !!merge <<: *baidu
  - name: 北京中联
    server: 220.181.33.174
    !!merge <<: *addons
  - name: 广州中联
    server: 220.181.111.189
    !!merge <<: *addons
  - name: 华南电信
    server: 180.101.50.249
    !!merge <<: *addons
  - name: 昆山联通
    server: 157.0.148.53
    !!merge <<: *addons
  - name: 郑州联通1
    server: 110.242.70.68
    !!merge <<: *addons
  - name: 郑州联通2
    server: 110.242.70.69
    !!merge <<: *addons
  - name: 郑州电信1
    server: 180.97.93.202
    !!merge <<: *addons
  - name: 郑州电信2
    server: 180.101.50.208
    !!merge <<: *addons
  - name: 郑州中联